export const products = [
  {
    id: "table-runner-green",
    name: "Table Runner",
    cat: "Kitchen & Dining",
    img: "table-runner.jpg",
    desc: "Soft, understated table textile designed to layer into everyday dining.",
    material: "Textile",
    size: "Multiple lengths",
  },
  {
    id: "table-runner-gold",
    name: "Table Runner",
    cat: "Kitchen & Dining",
    img: "table-runner-gold2.jpg",
    desc: "Soft, understated table textile designed to layer into everyday dining.",
    material: "Textile",
    size: "Multiple lengths",
  },
  {
    id: "matcha-ritual",
    name: "Matcha Ritual Set",
    cat: "Kitchen & Dining",
    img: "matcha-set.jpg",
    desc: "A considered set for preparing and enjoying matcha at home.",
    material: "Ceramic / bamboo / stainless steel",
    size: "Set",
  },
  {
    id: "mixing-bowls",
    name: "Mixing Bowl Collection",
    cat: "Kitchen & Dining",
    img: "mixing-bowls.jpg",
    desc: "A practical family of stainless steel bowls for everyday preparation.",
    material: "Stainless steel",
    size: "Multi-size set",
  },
  {
    id: "storage-bag",
    name: "Everyday Storage Bag",
    cat: "Home & Living",
    img: "storage-bag.jpg",
    desc: "Large-capacity storage for bedding, clothing and seasonal organisation.",
    material: "PP woven fabric",
    size: "92 L",
  },
  {
    id: "vacuum-storage",
    name: "Vacuum Storage Bags",
    cat: "Home & Living",
    img: "save-bag.jpg",
    desc: "Space-saving storage designed for seasonal clothing and textiles.",
    material: "PA + PE",
    size: "Multiple sizes",
  },
  {
    id: "suit-bags",
    name: "Suit Bags",
    cat: "Home & Living",
    img: "suit-bags.jpg",
    desc: "Spacious storage solution for organising suits and formal wear.",
    material: "TTextile",
    size: "Multiple sizes",
    size: "180",
  },

  {
    id: "coffee-cups",
    name: "Everyday Coffee Cups",
    cat: "Kitchen & Dining",
    img: "coffee-cup.jpg",
    desc: "500ml 304 Stainless Steel Camping Coffee Cup",
    material: "304 Stainless steel",
    size: "Approx. 500 ml",
  },
  {
    id: "steel-cups",
    name: "Everyday Steel Cups",
    cat: "Kitchen & Dining",
    img: "cup.jpg",
    desc: "Minimal stainless steel drinkware with a clean geometric profile.",
    material: "Stainless steel",
    size: "Approx. 470 ml",
  },
  {
    id: "resistance-bands",
    name: "Resistance Bands",
    cat: "Active Living",
    img: "resistance-band.jpg",
    desc: "A compact resistance training set for movement at home or on the go.",
    material: "TPE / textile",
    size: "Multiple resistance levels",
  },
];
